### ISSUE TITLE
Besluittype filteren op zaaktypen of informatieobjecttypen geeft internal server error

### ISSUE THREAD

**Issue by stevenbal** [VNG-Realisatie/gemma-zaken#1467]
# Bug

Als ik de lijst van `BesluitType`n in het ZTC probeer te filter of `zaaktypen` of `informatieobjecttypen`, krijg ik een internal server error:

```json
ObjectDoesNotExist at /api/v1/besluittypen
URL did not resolve

Request Method: GET
Request URL: http://172.17.0.1:8002/api/v1/besluittypen?catalogus=http://172.17.0.1:8002/api/v1/catalogussen/e627375d-7bfb-440a-8eb8-12465071c810&zaaktypen=http://172.17.0.1:8002/api/v1/zaaktypen/b0ddd76d-cc85-4da9-9a4c-6b4e3abd68ee&informatieobjecttypen=http://172.17.0.1:8002/api/v1/informatieobjecttypen/0174391f-18cc-4cfa-9266-25c20c29c71d&status=concept&page=1
Django Version: 2.2.4
Python Executable: /usr/local/bin/uwsgi
Python Version: 3.6.9
```

En in de logging van het ZTC zie ik de volgende exception:

```python
Internal Server Error: /api/v1/besluittypen
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/vng_api_common/utils.py", line 61, in get_viewset_for_path
   resolver_match = resolver.resolve(path)
File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 567, in resolve
   raise Resolver404({'path': path})
django.urls.exceptions.Resolver404: {'path': 'http://172.17.0.1:8002/api/v1/zaaktypen/b0ddd76d-cc85-4da9-9a4c-6b4e3abd68ee'}
```

Terwijl het zaaktype wel degelijk bestaat als ik hem zelf ophaal via de api:
```json
{
    "url": "http://172.17.0.1:8002/api/v1/zaaktypen/b0ddd76d-cc85-4da9-9a4c-6b4e3abd68ee",
    "identificatie": "1",
    "omschrijving": "zrc_tests_1",
    "omschrijvingGeneriek": "",
    "vertrouwelijkheidaanduiding": "openbaar",
    "doel": "test doel",
    "aanleiding": "test aanleiding",
    "toelichting": "",
    "indicatieInternOfExtern": "extern",
    "handelingInitiator": "indienen",
    "onderwerp": "openbare ruimte",
    "handelingBehandelaar": "behandelen",
    "doorlooptijd": "P10D",
    "servicenorm": null,
    "opschortingEnAanhoudingMogelijk": false,
    "verlengingMogelijk": true,
    "verlengingstermijn": "P5D",
    "trefwoorden": [],
    "publicatieIndicatie": false,
    "publicatietekst": "",
    "verantwoordingsrelatie": [],
    "productenOfDiensten": [
        "https://ref.tst.vng.cloud/standaard/"
    ],
    "selectielijstProcestype": "https://referentielijsten-api.vng.cloud/api/v1/procestypen/3030daa1-d516-4cd9-8276-ef0977e32b20",
    "referentieproces": {
        "naam": "test",
        "link": ""
    },
    "catalogus": "http://172.17.0.1:8002/api/v1/catalogussen/e627375d-7bfb-440a-8eb8-12465071c810",
    "statustypen": [],
    "resultaattypen": [],
    "eigenschappen": [],
    "informatieobjecttypen": [],
    "roltypen": [],
    "besluittypen": [
        "http://172.17.0.1:8002/api/v1/besluittypen/1e276482-f3f4-47b5-8110-2924f1a8570f"
    ],
    "deelzaaktypen": [],
    "gerelateerdeZaaktypen": [],
    "beginGeldigheid": "2019-01-01",
    "eindeGeldigheid": null,
    "versiedatum": "2019-01-01",
    "concept": false
}
```

**Comment by sergei-maertens** [comment]
PR was merged and deployed
