### ISSUE TITLE
Api test: test details niet zichtbaar

### ISSUE THREAD

**Issue by johannesbattjes** [VNG-Realisatie/gemma-zaken#1909]
# Bug

Ik heb twee test scenario's, 334 en 337.
Tot nu toe zijn mijn testen beide tests gefaald, maar 337 heeft ook enkele succesvolle API calls (kan ik zien in mijn eigen log). 
334 toont details met daarbij hoeveel goed/fout.
Maar bij 337 zie ik die niet.
Bovendien zie ik op de overzichtspagina van dit scenario deze fout staan (kolom action):

Traceback (most recent call last): File "/srv/sites/vng-production/src/vng/servervalidation/task.py", line 93, in execute_test file_html, file_json = nm.execute_test() File "/srv/sites/vng-production/src/vng/utils/newman.py", line 65, in execute_test assert False, error AssertionError: b'error: Script execution timed out after 30000ms\n\n'

Mijn login naam is johannes.battjes@roxit.nl

**Comment by michielverhoef** [comment]
@HenriKorver  Dit klinkt als een fout in het API Test Platform, niet als een fout in de testset.

**Comment by HenriKorver** [comment]
@johannesbattjes Dit is een issue van een jaar gelden, speelt het probleem nog steeds? Het probleem met die 30-seconden timeout speelde ook een tijdje geleden voor OpenZaak, dus de duur daarvan is opgehoogd naar 180 seconden. Sommige scripts/aanroepen duren wat langer dan waar we tijdens de bouw rekening mee hielden, dus hopelijk helpt het. Maar wat ook zou kunnen is dat de omgeving van Roxit niet bereikbaar is voor api-test.nl, in dat geval krijg je ook een timeout.

**Comment by terborg** [comment]
Met het stopzetten van het beheer en de ontwikkeling van de referentie-implementatie(s) is ook api-test.nl stopgezet. Dit issue wordt daarom gesloten.
