### ISSUE TITLE
Notificaties API create_abonnement geeft HTTP 500 bij ontbreken van optionele "filters" property

### ISSUE THREAD

**Issue by MLenterman** [VNG-Realisatie/gemma-zaken#1934]
# Bug

Bij een [create_abonnement](https://notificaties-api.vng.cloud/api/v1/schema/#operation/abonnement_create) komt er een HTTP 500 terug wanneer de "filters" property mist. Volgens de documentatie niet required.

Body met als resultaat HTTP 500:
``` json
{
  "callbackUrl": "<callback>",
  "auth": "<auth>",
  "kanalen": [
    {
      "naam": "zaken"
    }
  ]
}
```

Body met als resultaat HTTP 201:
``` json
{
  "callbackUrl": "<callback>",
  "auth": "<auth>",
  "kanalen": [
    {
      "filters":{
          "test": "test"
      },
      "naam": "zaken"
    }
  ]
}
```

Foutmelding in notificaties API web container:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/mixins.py", line 20, in create
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 236, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 437, in run_validation
    value = self.validate(value)
  File "./nrc/api/serializers.py", line 110, in validate
    abon_filter_names = [f.key for f in group_data["filters"]]
KeyError: 'filters'

[pid: 16|app: 0|req: 5/7] <IP> () {40 vars in 939 bytes} [Mon Jan 24 12:27:16 2022] POST /api/v1/abonnement => generated 220 bytes in 743 msecs (HTTP/1.1 500) 5 headers in 173 bytes (1 switches on core 0)
```

**Waar staan de componenten gehost? (ref.tst.vng.cloud of zelf binnen eigen organisatie)**
Binnen eigen organisatie in een Docker container.

**Welke claims/payload bevat je JWT?**
notificaties.consumeren | notificaties.publiceren

**Comment by michielverhoef** [comment]
Momenteel is dit niet oplosbaar in de referentie implementaties. Autorisaties wordt afgehandeld in de zgn. [VNG API Common](https://github.com/VNG-Realisatie/vng-api-common) laag en deze is dusdanig verouderd dat we hier even geen aanpassingen in kunnen maken.

Wat wel kan is de Notificaties API OAS yaml aanpassen. De referentie implementatie kan dan echter niet bijgewerkt worden.

**Comment by terborg** [comment]
Het beheer en de ontwikkeling van de referentie-implementatie(s) is stopgezet. Dit issue wordt daarom gesloten.
