### ISSUE TITLE
Behandel header parameters zonder "required" veld in OpenAPI schema van externe services als "required: false"

### ISSUE THREAD

**Issue by JesseRoxit** [VNG-Realisatie/gemma-zaken#1935]
# Bug
Tijdens het evalueren van het OpenAPI scheme van externe services treedt er een exception op wanneer bij een header parameter het veld "required" ontbreekt. In OpenAPI 3.0 zijn parameters zonder het veld "required" standaard optioneel. Dit is dan ook mijn suggestie: behandel header parameters zonder het veld required standaard als optioneel.

Dit issue is gevonden door in OpenZaak een custom selectielijst component te configureren waarbij het OpenAPI schema geen veld "required" bevat voor optionele header parameters.

# Repro steps

1. Clone OpenZaak repo
2. Run docker-compose up
3. Navigeer naar http://localhost:8000/admin/config/external/
4. Laat het OAS schema veld verwijzen naar een OpenAPI schema die header parameters bevat zonder het veld "required"
5. Maak een catalogi aan
6. Maak een zaaktype aan
7. Maak een resultaattype
8. 💥

# Stacktrace
```
2022-01-25 12:31:08,580 ERROR django.request  Internal Server Error: /catalogi/api/v1/resultaattypen

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 220, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 421, in run_validation
    self.run_validators(value)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 454, in run_validators
    super().run_validators(to_validate)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/fields.py", line 593, in run_validators
    validator(value)
  File "./openzaak/components/catalogi/api/validators.py", line 112, in __call__
    selectielijstklasse = fetch_object("resultaat", selectielijstklasse_url)
  File "./openzaak/client.py", line 17, in fetch_object
    obj = client.retrieve(resource, url=url)
  File "/usr/local/lib/python3.7/site-packages/zds_client/client.py", line 289, in retrieve
    return self.request(url, operation_id, request_kwargs=request_kwargs)
  File "/usr/local/lib/python3.7/site-packages/zds_client/client.py", line 201, in request
    schema_headers = get_headers(self.schema, operation)
  File "/usr/local/lib/python3.7/site-packages/zds_client/schema.py", line 156, in get_headers
    method_parameters = filter_header_params(method.get("parameters", []), spec)
  File "/usr/local/lib/python3.7/site-packages/zds_client/schema.py", line 134, in filter_header_params
    header_regular_parameters = filter_header_regular_params(regular_parameters)
  File "/usr/local/lib/python3.7/site-packages/zds_client/schema.py", line 100, in filter_header_regular_params
    return [param for param in params if param["in"] == "header" and param["required"]]
  File "/usr/local/lib/python3.7/site-packages/zds_client/schema.py", line 100, in <listcomp>
    return [param for param in params if param["in"] == "header" and param["required"]]
	
KeyError: 'required'

```

**Comment by JesseRoxit** [comment]
Ik heb dit issue in de verkeerde repository aangemaakt en kom erachter dat hetzelfde issue al in de goede repo is geregistreerd: https://github.com/VNG-Realisatie/gemma-zds-client/issues/24
