### ISSUE TITLE
'BestandsDeel' object has no attribute 'lock' (versie 1.3.1)

### ISSUE THREAD

**Issue by rderooij** [VNG-Realisatie/gemma-zaken#2336]
Ik test momenteel lock attribuut met versie 1.3.1 en ik krijg een Internal Server Error. Deze foutmelding krijg ik niet met 1.4.1. Het lijkt erop dat er nog wat code ontbreekt in de 1.3.1 versie. 

```
Request method: POST
Request URI:    http://drc.local:8000/api/v1/enkelvoudiginformatieobjecten
Proxy:                  <none>
Request params: <none>
Query params:   <none>
Form params:    <none>
Path params:    <none>
Headers:                Accept=application/json, application/javascript, text/javascript, text/json
                                Authorization=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkcmNfYXBpX3Rlc3RzIiwiZXhwIjoxNjk0NTE1OTc2LCJpYXQiOjE2OTQ1MTIzNzYsImNsaWVudF9pZCI6ImRyY19hcGlfdGVzdHMifQ.w326KToHe1ziPed_82ZEBdeQi4cZC9UlArAHdc6CRQk
                                Content-Type=application/json; charset=UTF-8
Cookies:                <none>
Multiparts:             <none>
Body:
{
    "beschrijving": "test_beschrijving",
    "identificatie": "198b999c-32fe-45ba-9564-a0be66d9b8d7",
    "bronorganisatie": "159351741",
    "bestandsomvang": 21,
    "link": "http://een.link",
    "taal": "eng",
    "auteur": "test_auteur",
    "formaat": "txt",
    "inhoud": null,
    "titel": "detailed summary",
    "vertrouwelijkheidaanduiding": "openbaar",
    "informatieobjecttype": "http://open-zaak.local:8000/catalogi/api/v1/informatieobjecttypen/ff7eaef0-d2e1-4a3c-941e-7df3bbb1e0f5",
    "bestandsnaam": "dummy.txt",
    "creatiedatum": "2018-06-27"
}
HTTP/1.1 500 Internal Server Error
Content-Type: text/plain; charset=utf-8
X-Frame-Options: DENY
Content-Length: 25365
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin

AttributeError at /api/v1/enkelvoudiginformatieobjecten
Got AttributeError when attempting to get a value for field `lock` on serializer `BestandsDeelSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `BestandsDeel` instance.
Original exception text was: 'BestandsDeel' object has no attribute 'lock'.

Request Method: POST
Request URL: http://drc.local:8000/api/v1/enkelvoudiginformatieobjecten
Django Version: 3.2.13
Python Executable: /usr/local/bin/uwsgi
Python Version: 3.9.18
Python Path: ['.', '', '/usr/local/lib/python39.zip', '/usr/local/lib/python3.9', '/usr/local/lib/python3.9/lib-dynload', '/usr/local/lib/python3.9/site-packages']
Server time: Tue, 12 Sep 2023 09:52:57 +0000
Installed Applications:
['django.contrib.contenttypes',
 'django.contrib.auth',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'axes',
 'django_filters',
 'corsheaders',
 'vng_api_common',
 'vng_api_common.authorizations',
 'vng_api_common.audittrails',
 'vng_api_common.notifications',
 'drf_spectacular',
 'rest_framework',
 'django_markup',
 'solo',
 'simple_certmanager',
 'zgw_consumers',
 'notifications_api_common',
 'privates',
 'drc.accounts',
 'drc.api',
 'drc.datamodel',
 'drc.utils']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'drc.utils.middleware.LogHeadersMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'vng_api_common.middleware.AuthMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'vng_api_common.middleware.APIVersionHeaderMiddleware',
 'axes.middleware.AxesMiddleware']


Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/rest_framework/fields.py", line 457, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/fields.py", line 97, in get_attribute
    instance = getattr(instance, attr)

During handling of the above exception ('BestandsDeel' object has no attribute 'lock'), another exception occurred:
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/drf_spectacular/drainage.py", line 159, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/notifications_api_common/viewsets.py", line 210, in create
    response = super().create(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/vng_api_common/audittrails/viewsets.py", line 101, in create
    response = super().create(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 20, in create
    headers = self.get_success_headers(serializer.data)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 548, in data
    ret = super().data
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 515, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 664, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 502, in to_representation
    attribute = field.get_attribute(instance)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/fields.py", line 490, in get_attribute
    raise type(exc)(msg)

Exception Type: AttributeError at /api/v1/enkelvoudiginformatieobjecten
Exception Value: Got AttributeError when attempting to get a value for field `lock` on serializer `BestandsDeelSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `BestandsDeel` instance.
Original exception text was: 'BestandsDeel' object has no attribute 'lock'.
Request information:
USER: AnonymousUser

GET: No GET data

POST: No POST data

FILES: No FILES data

COOKIES: No cookie data
```

**Comment by michielverhoef** [comment]
Is opgelost met  https://github.com/VNG-Realisatie/gemma-zaken/milestone/34
